// @ts-nocheck
import { browser } from 'fumadocs-mdx/runtime/browser';
import type * as Config from '../source.config';

const create = browser<typeof Config, import("fumadocs-mdx/runtime/types").InternalTypeConfig & {
  DocData: {
  }
}>();
const browserCollections = {
  docs: create.doc("docs", {"index.mdx": () => import("../content/docs/index.mdx?collection=docs"), "reference/agents.mdx": () => import("../content/docs/reference/agents.mdx?collection=docs"), "reference/files.mdx": () => import("../content/docs/reference/files.mdx?collection=docs"), "reference/install.mdx": () => import("../content/docs/reference/install.mdx?collection=docs"), "reference/telemetry.mdx": () => import("../content/docs/reference/telemetry.mdx?collection=docs"), "reference/updates.mdx": () => import("../content/docs/reference/updates.mdx?collection=docs"), "features/(hosts)/advanced-host-options.mdx": () => import("../content/docs/features/(hosts)/advanced-host-options.mdx?collection=docs"), "features/(hosts)/connections.mdx": () => import("../content/docs/features/(hosts)/connections.mdx?collection=docs"), "features/(hosts)/history-import.mdx": () => import("../content/docs/features/(hosts)/history-import.mdx?collection=docs"), "features/(hosts)/host-management.mdx": () => import("../content/docs/features/(hosts)/host-management.mdx?collection=docs"), "features/(hosts)/host-picker.mdx": () => import("../content/docs/features/(hosts)/host-picker.mdx?collection=docs"), "features/(hosts)/ssh-config.mdx": () => import("../content/docs/features/(hosts)/ssh-config.mdx?collection=docs"), "features/(keys)/key-selector.mdx": () => import("../content/docs/features/(keys)/key-selector.mdx?collection=docs"), "features/(keys)/keys.mdx": () => import("../content/docs/features/(keys)/keys.mdx?collection=docs"), "features/(other)/cli.mdx": () => import("../content/docs/features/(other)/cli.mdx?collection=docs"), "features/(other)/mobile-view.mdx": () => import("../content/docs/features/(other)/mobile-view.mdx?collection=docs"), "features/(other)/shortcuts.mdx": () => import("../content/docs/features/(other)/shortcuts.mdx?collection=docs"), "features/(sync)/aws.mdx": () => import("../content/docs/features/(sync)/aws.mdx?collection=docs"), "features/(sync)/azure.mdx": () => import("../content/docs/features/(sync)/azure.mdx?collection=docs"), "features/(sync)/gcp.mdx": () => import("../content/docs/features/(sync)/gcp.mdx?collection=docs"), }),
};
export default browserCollections;