package azure

import (
	"context"
	"errors"
	"fmt"
	"os"
	"path/filepath"
	"strings"
)

type EnsureConfig struct {
	Home           string
	ManagedKeys    string
	AzureDir       string
	DefaultSSHUser string
	Status         func(string)
}

type EnsureResult struct {
	User            string
	IdentityFile    string
	CertificateFile string
	IdentitiesOnly  bool
}

func reportStatus(status func(string), message string) {
	if status != nil && strings.TrimSpace(message) != "" {
		status(message)
	}
}

func (c *Client) EnsureAccess(ctx context.Context, syncID string, cfg EnsureConfig) (EnsureResult, error) {
	if cfg.Home == "" {
		home, err := os.UserHomeDir()
		if err != nil {
			return EnsureResult{}, fmt.Errorf("resolve home directory: %w", err)
		}
		cfg.Home = home
	}
	subscriptionID, resourceGroup, name, err := ParseSyncID(syncID)
	if err != nil {
		return EnsureResult{}, err
	}
	if err := c.CheckAvailable(ctx); err != nil {
		return EnsureResult{}, err
	}
	reportStatus(cfg.Status, "Checking Azure VM access…")
	var vm vmRecord
	if err := c.runJSON(ctx, &vm, "vm", "show", "--show-details", "--ids", syncID,
		"--subscription", subscriptionID, "--output", "json", "--only-show-errors"); err != nil {
		return EnsureResult{}, fmt.Errorf("describe Azure VM: %w", err)
	}
	if vm.ID == "" || !strings.EqualFold(vm.ID, syncID) {
		return EnsureResult{}, fmt.Errorf("could not find Azure VM %s", name)
	}
	userName := strings.TrimSpace(cfg.DefaultSSHUser)
	if userName == "" {
		userName = strings.TrimSpace(vm.OSProfile.AdminUsername)
	}
	if identity := matchLocalKey(vmSSHKeys(vm), cfg.Home, cfg.ManagedKeys); identity != "" {
		if userName == "" {
			return EnsureResult{}, fmt.Errorf("could not determine the Azure VM SSH user; set a default SSH user in Sync")
		}
		reportStatus(cfg.Status, "Using local Azure SSH key…")
		return EnsureResult{User: userName, IdentityFile: identity, IdentitiesOnly: true}, nil
	}

	if err := c.CheckExtension(ctx, "ssh"); err != nil {
		return EnsureResult{}, err
	}
	if _, err := c.run(ctx, "vm", "extension", "show", "--resource-group", resourceGroup,
		"--vm-name", name, "--name", "AADSSHLoginForLinux", "--subscription", subscriptionID,
		"--output", "json", "--only-show-errors"); err != nil {
		return EnsureResult{}, fmt.Errorf("no matching local SSH key and Microsoft Entra SSH login is not enabled for %s: %w", name, err)
	}

	azureDir := cfg.AzureDir
	if azureDir == "" {
		azureDir = filepath.Join(cfg.Home, ".ssh", "bast", "azure")
	}
	if err := os.MkdirAll(azureDir, 0700); err != nil {
		return EnsureResult{}, fmt.Errorf("create Azure SSH directory: %w", err)
	}
	if err := os.Chmod(azureDir, 0700); err != nil {
		return EnsureResult{}, fmt.Errorf("secure Azure SSH directory: %w", err)
	}
	temp, err := os.CreateTemp(azureDir, ".entra-config-*")
	if err != nil {
		return EnsureResult{}, fmt.Errorf("create temporary Azure SSH config: %w", err)
	}
	configPath := temp.Name()
	if closeErr := temp.Close(); closeErr != nil {
		return EnsureResult{}, closeErr
	}
	defer os.Remove(configPath)

	reportStatus(cfg.Status, "Requesting a Microsoft Entra SSH certificate…")
	if _, err := c.run(ctx, "ssh", "config", "--file", configPath, "--overwrite",
		"--resource-group", resourceGroup, "--name", name, "--subscription", subscriptionID,
		"--resource-type", "Microsoft.Compute/virtualMachines",
		"--keys-destination-folder", azureDir, "--output", "none", "--only-show-errors"); err != nil {
		return EnsureResult{}, fmt.Errorf("create Microsoft Entra SSH certificate: %w", err)
	}
	generated, err := parseGeneratedSSHConfig(configPath)
	if err != nil {
		return EnsureResult{}, err
	}
	if generated.User == "" || generated.IdentityFile == "" || generated.CertificateFile == "" {
		return EnsureResult{}, errors.New("incomplete SSH configuration generated by Azure CLI")
	}
	resolvedAzureDir, err := filepath.EvalSymlinks(azureDir)
	if err != nil {
		return EnsureResult{}, fmt.Errorf("resolve Azure SSH directory: %w", err)
	}
	for path, mode := range map[string]os.FileMode{generated.IdentityFile: 0600, generated.CertificateFile: 0644} {
		expanded := expandHome(path, cfg.Home)
		resolved, err := filepath.EvalSymlinks(expanded)
		if err != nil {
			return EnsureResult{}, fmt.Errorf("resolve Azure SSH material: %w", err)
		}
		if !pathInside(resolved, resolvedAzureDir) {
			return EnsureResult{}, fmt.Errorf("refusing SSH material generated by Azure CLI outside %s", azureDir)
		}
		if err := os.Chmod(resolved, mode); err != nil {
			return EnsureResult{}, fmt.Errorf("secure Azure SSH material: %w", err)
		}
	}
	return EnsureResult{
		User: generated.User, IdentityFile: shortenHome(expandHome(generated.IdentityFile, cfg.Home), cfg.Home),
		CertificateFile: shortenHome(expandHome(generated.CertificateFile, cfg.Home), cfg.Home), IdentitiesOnly: true,
	}, nil
}

type generatedSSHConfig struct {
	User            string
	IdentityFile    string
	CertificateFile string
}

func parseGeneratedSSHConfig(path string) (generatedSSHConfig, error) {
	data, err := os.ReadFile(path)
	if err != nil {
		return generatedSSHConfig{}, fmt.Errorf("read Azure SSH config: %w", err)
	}
	var result generatedSSHConfig
	inHost := false
	for _, line := range strings.Split(string(data), "\n") {
		fields, fieldErr := configFields(strings.TrimSpace(line))
		if fieldErr != nil || len(fields) == 0 {
			continue
		}
		if strings.EqualFold(fields[0], "Host") {
			if inHost {
				break
			}
			inHost = len(fields) > 1
			continue
		}
		if !inHost || len(fields) < 2 {
			continue
		}
		switch strings.ToLower(fields[0]) {
		case "user":
			result.User = fields[1]
		case "identityfile":
			result.IdentityFile = fields[1]
		case "certificatefile":
			result.CertificateFile = fields[1]
		}
	}
	return result, nil
}

func configFields(line string) ([]string, error) {
	var result []string
	var current strings.Builder
	var quote rune
	escaped := false
	flush := func() {
		if current.Len() > 0 {
			result = append(result, current.String())
			current.Reset()
		}
	}
	for _, r := range line {
		if escaped {
			current.WriteRune(r)
			escaped = false
			continue
		}
		if r == '\\' {
			escaped = true
			continue
		}
		if quote != 0 {
			if r == quote {
				quote = 0
			} else {
				current.WriteRune(r)
			}
			continue
		}
		if r == '\'' || r == '"' {
			quote = r
			continue
		}
		if r == '#' {
			break
		}
		if r == ' ' || r == '\t' {
			flush()
			continue
		}
		current.WriteRune(r)
	}
	if escaped || quote != 0 {
		return nil, fmt.Errorf("unterminated escape or quote")
	}
	flush()
	return result, nil
}

func expandHome(path, home string) string {
	if path == "~" {
		return home
	}
	if strings.HasPrefix(path, "~/") {
		return filepath.Join(home, filepath.FromSlash(strings.TrimPrefix(path, "~/")))
	}
	return path
}

func pathInside(path, dir string) bool {
	absPath, err := filepath.Abs(path)
	if err != nil {
		return false
	}
	absDir, err := filepath.Abs(dir)
	if err != nil {
		return false
	}
	rel, err := filepath.Rel(absDir, absPath)
	return err == nil && rel != ".." && !strings.HasPrefix(rel, ".."+string(filepath.Separator))
}
